"""Static protocol definitions for the Voltron UART decoder."""

from __future__ import annotations

SOF = b"\x5a\xa5"

DEVICES = {
    0x20: "ECU", 0x21: "Dashboard", 0x22: "BMS", 0x23: "BMS2",
    0x24: "Module-24", 0x2F: "Module-2F", 0x3D: "IoT", 0x3E: "BLE", 0x3F: "CAN",
}

COMMANDS = {
    0x01: "RD", 0x02: "WR", 0x03: "WR_NR", 0x04: "ACK_RD/SYNC",
    0x05: "ACK_WR/EXRD", 0x06: "CLEAR_ERROR", 0x0B: "IAP_ACK/POWER_OFF",
    0x10: "CTL", 0x20: "DRV", 0x30: "AHRS", 0x55: "HEARTBEAT",
    0x56: "TEST_MODE", 0x57: "ACT", 0x58: "UNACT", 0x59: "ACT_ALL",
    0x5A: "ACT_BATTERY_ONLY", 0x5B: "UNACT_BATTERY_ONLY",
}

ECU_INDEX = {
    0x10: "SERIAL", 0x1A: "FW_VERSION", 0x1B: "ERROR", 0x1C: "ALARM",
    0x1D: "BOOL_FLAGS", 0x1F: "WORK_MODE", 0x20: "STEP_SWITCH",
    0x21: "LINK_ANGLE", 0x22: "BTC", 0x23: "CURRENT_LIMIT_SPEED",
    0x25: "PRODUCTION_RIDE_MILEAGE", 0x26: "SPEED",
    0x29: "RIDE_MILEAGE_LOW", 0x2A: "RIDE_MILEAGE_HIGH",
    0x2D: "REMAINING_MILEAGE_LOW", 0x2E: "REMAINING_MILEAGE_HIGH",
    0x34: "RIDE_TIME_LOW", 0x35: "RIDE_TIME_HIGH",
    0x3E: "BODY_TEMP", 0x3F: "BAT1_TEMP", 0x40: "BAT2_TEMP",
    0x47: "DRIVER_VOLTAGE", 0x48: "BATTERY_VOLTAGE_1",
    0x49: "BATTERY_VOLTAGE_2", 0x4A: "SYSTEM_12V", 0x4B: "SYSTEM_5V",
    0x50: "SYSTEM_CURRENT", 0x70: "LOCK", 0x71: "UNLOCK",
    0x72: "SPEED_LIMIT", 0x73: "NORMAL_SPEED", 0x74: "LIMITED_SPEED",
    0x75: "CALIBRATE_GYRO", 0x76: "CALIBRATE_EULER", 0x77: "ENGINE",
    0x78: "REBOOT", 0x79: "POWER_OFF", 0x7A: "REMOTE_CONTROL",
    0x7B: "REMOTE_SPEED", 0x7C: "REMOTE_DIFF_SPEED", 0x7D: "REMOTE_MAX_SPEED",
    0xC6: "LED_MODE", 0xC7: "LED_COUNT", 0xC8: "LED_COLOR_1",
    0xCA: "LED_COLOR_2", 0xCC: "LED_COLOR_3", 0xCE: "LED_COLOR_4",
}

BMS_INDEX = {
    0x10: "SERIAL", 0x17: "FW_VERSION", 0x18: "DISCHARGE_FULL_CAPACITY",
    0x19: "CURRENT_FULL_CAPACITY", 0x1A: "DISCHARGE_VOLTAGE",
    0x1B: "DISCHARGE_LOOP", 0x1C: "CHARGE_COUNT", 0x20: "PRODUCTION_DATE",
    0x22: "FRONT_CODE", 0x23: "BACK_CODE", 0x30: "STATUS",
    0x31: "CURRENT_CAPACITY", 0x33: "CURRENT", 0x34: "VOLTAGE",
    0x35: "TEMPERATURE/HEALTH", 0x36: "BALANCE_STATE",
    0x37: "OVER_DISCHARGE_STATE", 0x38: "OVER_CHARGE_STATE",
    0x39: "COULOMB_CAPACITY", 0x3A: "VOLTAGE_CAPACITY",
    0x3B: "CAPACITY_HEALTH", 0x3D: "CTO_INDEX", 0x3E: "CAPACITY_PERCENT",
    0x40: "CELL_VOLTAGES", 0x50: "BEEN_ACTIVATED",
    0x51: "PCB_VERSION/TEMP34/TEMP56", 0x7B: "WARNING",
}

VEHICLE_STATES = {4: "UNLOCKED", 5: "LOCKED", 20: "CHARGING"}

ECU_ERRORS = {
    0: "NONE", 10: "DASHBOARD_CONTROLLER_COMMUNICATION",
    11: "MOTOR_A_PHASE_CURRENT_SAMPLING", 12: "MOTOR_B_PHASE_CURRENT_SAMPLING",
    13: "MOTOR_C_PHASE_CURRENT_SAMPLING", 14: "THROTTLE_HALL",
    15: "LEFT_BRAKE_HALL", 16: "RIGHT_BRAKE_HALL", 18: "MOTOR_HALL",
    19: "BATTERY_VOLTAGE_DETECTION", 21: "BMS_COMMUNICATION",
    22: "BMS_PASSWORD", 23: "BMS_SERIAL_NUMBER", 24: "SYSTEM_VOLTAGE_DETECTION",
    26: "FLASH_SAVE", 27: "CONTROLLER_PASSWORD", 31: "PROGRAM_EXECUTION",
    32: "IOT_CONTROLLER_TIMEOUT", 35: "CONTROLLER_SERIAL_NUMBER",
    39: "BATTERY_TEMPERATURE_SENSOR", 40: "CONTROLLER_TEMPERATURE_SENSOR",
    41: "MOTOR_TEMPERATURE", 50: "CONTROLLER_BMS_MISMATCH",
    51: "CONTROLLER_DASHBOARD_MISMATCH", 52: "CONTROLLER_LOCK_MISMATCH",
    54: "CONTROLLER_LOCK_COMMUNICATION", 55: "COMPARTMENT_COVER_OPEN",
}

ECU_FLAG_BITS = {
    0: "battery_compartment_closed",
    2: "unknown_bit_2",
    3: "left_indicator_on",
    4: "right_indicator_on",
}

# Very weak discarded hypothesis: bit 2 may once have correlated with GPS no-fix.
# Keep the clue here only.  It remains UNKNOWN in every decoded/user-facing view.
FLAG_UNKNOWN_BIT_2 = 0x04

ECU_FLAGS_INTERPRETED_MASK = (1 << 0) | (1 << 3) | (1 << 4)
BMS_CURRENT_SCALE_A = 0.01
BMS_VOLTAGE_SCALE_V = 0.01
BATTERY_REST_CURRENT_THRESHOLD_A = 1.5
BATTERY_REST_MOTOR_POWER_THRESHOLD_W = 20.0
BATTERY_RESISTANCE_MIN_CURRENT_A = 2.0
BATTERY_BASELINE_MIN_SAMPLES = 2
BATTERY_BASELINE_WINDOW_SAMPLES = 3
